SET SERVEROUTPUT ON

DECLARE

Y NUMBER;
V1 NUMBER;

ENO EMP.EMPNO%TYPE;
NM EMP.ENAME%TYPE;
V EMP.HIREDATE%TYPE;

CURSOR S(D NUMBER) IS SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE EXTRACT(YEAR FROM HIREDATE)=D;

E EXCEPTION;

BEGIN

V1:='&U';
OPEN S(V1);

Y:=0;

FETCH S INTO ENO,NM,V;

IF(S%NOTFOUND) THEN
RAISE E;
END IF;

DBMS_OUTPUT.PUT_LINE('EMPNO'||'         '||'ENAME'||'         '||'HIREDATE');
DBMS_OUTPUT.PUT_LINE('----------------------------------------');

LOOP

DBMS_OUTPUT.PUT_LINE(ENO||'         '||NM||'         '||V);

Y:=Y+1;

FETCH S INTO ENO,NM,V;
EXIT WHEN S%NOTFOUND;

END LOOP;

DBMS_OUTPUT.PUT_LINE('----------------------------------------');
DBMS_OUTPUT.PUT_LINE('TOTAL NUMBER OF EMPLOYEE='||Y);
CLOSE S;

EXCEPTION
WHEN E THEN
DBMS_OUTPUT.PUT_LINE('INVALID HIREDATE');

END;
/
