SET SERVEROUTPUT ON

DECLARE
Y NUMBER;
A NUMBER;

CURSOR S IS SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE EXTRACT(YEAR FROM HIREDATE)='&A';
E EXCEPTION;

BEGIN
Y:=0;

DBMS_OUTPUT.PUT_LINE('EMPNO'||'         '||'ENAME'||'         '||'HIREDATE');
DBMS_OUTPUT.PUT_LINE('----------------------------------------');

FOR I IN S
LOOP

DBMS_OUTPUT.PUT_LINE(I.EMPNO||'         '||I.ENAME||'         '||I.HIREDATE);

Y:=S%ROWCOUNT;

END LOOP;

IF(Y=0) THEN
RAISE E;
END IF;

DBMS_OUTPUT.PUT_LINE('----------------------------------------');
DBMS_OUTPUT.PUT_LINE('TOTAL NUMBER OF EMPLOYEE='||Y);
DBMS_OUTPUT.PUT_LINE('----------------------------------------');

EXCEPTION
WHEN E THEN
DBMS_OUTPUT.PUT_LINE('INVALID HIREDATE');

END;
/
