SET SERVEROUTPUT ON

DECLARE

X NUMBER;
Y VARCHAR(4);

ENM EMP.ENAME%TYPE;
ENO EMP.EMPNO%TYPE;
DT EMP.HIREDATE%TYPE;

CURSOR Q IS SELECT DISTINCT TO_CHAR(HIREDATE,'YYYY') YR FROM EMP;


CURSOR S(D VARCHAR) IS SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE TO_CHAR(HIREDATE,'YYYY')=D;

E EXCEPTION;

BEGIN

OPEN Q;

LOOP

FETCH Q INTO Y;

EXIT WHEN Q%NOTFOUND;

OPEN S(Y);

X:=0;

DBMS_OUTPUT.PUT_LINE('YEAR :'||Y);
DBMS_OUTPUT.PUT_LINE('EMPNO'||'         '||'ENAME'||'         '||'HIREDATE');
DBMS_OUTPUT.PUT_LINE('----------------------------------------');

LOOP

FETCH S INTO ENO,ENM,DT;
EXIT WHEN S%NOTFOUND;

DBMS_OUTPUT.PUT_LINE(ENO||'         '||ENM||'         '||DT);

X:=X+1;

END LOOP;

DBMS_OUTPUT.PUT_LINE('----------------------------------------');
DBMS_OUTPUT.PUT_LINE('TOTAL NUMBER OF EMPLOYEE='||X);
DBMS_OUTPUT.PUT_LINE('----------------------------------------');

CLOSE S;

END LOOP;

CLOSE Q;

EXCEPTION
WHEN E THEN
DBMS_OUTPUT.PUT_LINE('INVALID HIREDATE');

END;
/
