CREATE OR REPLACE
TRIGGER TR3

AFTER INSERT

ON TRANSACTION1

FOR EACH ROW

BEGIN

IF (:NEW.T='D') THEN
	UPDATE ACCOUNT1 SET BALANCE=(BALANCE+:NEW.AMOUNT)
	WHERE ACNO=:NEW.ACNO;
ELSIF (:NEW.T='w') THEN
	UPDATE ACCOUNT1 SET BALANCE=(BALANCE-:NEW.AMOUNT) 
	WHERE ACNO=:NEW.ACNO and BALANCE-:NEW.AMOUNT>=1000;
END IF;

END;
/

